name: Lab2 CI

on:
 workflow_dispatch:
  # push:
  #   branches: 
  #      - '*lab2*'
  # pull_request:
  #   branches: 
  #     - '*lab2*' 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kmhswimgirl/rbe3002-autograder:test

    steps:
     - name: what directories do i have?
       run: |
        echo "ls -a"
      
     
    #  - name: Clone repo using git to absolute path
    #    run: |
    #     git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kmhswimgirl/RBE3002_ros2.git -b 32-clean-up /home/runner/ros2_ws/src
    #  - name: Build ROS workspace
    #    run: |
    #       cd ~/ros2_ws
    #       colcon build --symlink-install
    #       source install/setup.bash
    #  - name: run lab2 individual tests
    #    run:  |
    #       pytest ~ros2_ws/src/rbe3002_tests/test/lab2/test_drive.py -v
          
          
