name: Lab2 CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kmhswimgirl/rbe3002-autograder:test

    steps:
      - name: Clone repo into src directory inside container
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kmhswimgirl/RBE3002_ros2.git /root/ros2_ws/src -b 32-clean-up

      - name: Build ROS workspace
        run: |
          cd /root/ros2_ws
          colcon build --symlink-install
          source /root/ros2_ws/install/setup.bash

      - name: Run lab2 individual tests
        run: |
          pytest /root/ros2_ws/src/rbe3002_tests/test/lab2/test_drive.py -v 
