name: Lab2 CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kmhswimgirl/rbe3002-autograder:test

    steps:
      - name: Clone repo into src directory inside container
        shell: bash
        run: |
          git clone https://x-access-token:${{ secrets.RBE3002_ros2_KEY }}@github.com/kmhswimgirl/RBE3002_ros2.git /root/ros2_ws/src -b 32-clean-up

      - name: Build ROS workspace
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd /root/ros2_ws
          colcon build --symlink-install --packages-ignore rbe3002_interfaces
          source /root/ros2_ws/install/setup.bash
          
      - name: see entire file tree
        shell: bash
        run: |
          tree /

      - name: Run lab2 individual tests
        shell: bash
        run: |
          ls -l /root/ros2_ws/src/rbe3002_tests/test/lab2/
          pytest test/lab2/test_drive.py -v 
